[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sim_erice"
version = "0.1"

[tool.setuptools.packages.find]
where = ["."]
include = ["sim_erice*"]

[project.scripts]
"simtbx.sim_view" = "sim_erice.command_line.sim_view:main"

